server:
  port: 8080

spring:
  application:
    name: product-service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  profiles:
    include:
      - common
    active: default
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  data:
    redis:
#      host: redis-u44lkt.serverless.apn2.cache.amazonaws.com # 서버리스 Redis
      host: 52.78.140.152 # Redis 인스턴스
      port: 6379
      ssl:
         enabled: false # AWS 서버리스 Redis는 TLS 필수
#        enabled: true # AWS 서버리스 Redis는 TLS 필수

aws:
  s3:
    access-key: ${AWS_S3_ACCESS_KEY}
    secret-key: ${AWS_S3_SECRET_KEY}

stock:
  find:
    feign-endpoint: ${STOCK_SERVER_URL:http://localhost:9992}

order:
  find:
    feign-endpoint: ${ORDER_SERVER_URL:http://localhost:9999}

