spring:
  application:
    name: order-service
  profiles:
    active: default
    include:
      - common
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/emotional_cart}?useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:1234}
  data:
    redis:
      host: ${REDIS_SERVER_HOST:localhost}   # Redis server IP address
      port: ${REDIS_SERVER_PORT:6379}             # Redis server port
      timeout: 2000           # Connection timeout (in milliseconds)
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
        generate_statistics: true
        id:
          new_generator_mappings: true
  flyway:
    enabled: false
server:
  port: 9999
product:
  find:
    feign-endpoint: ${PRODUCT_SERVER_URL:http://localhost:8080}
stock:
  find:
    feign-endpoint: ${STOCK_SERVER_URL:http://localhost:9992}
app:
  allow-domains:
    - https://order-api.emmotional-cart.click