spring:
  application:
    name: member-service
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/emotional_cart}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: default
    group:
      default:
        - common
  jpa:
    hibernate:
      ddl-auto: none  # (옵션: create, update, validate, none. 개발 시 `update` 추천)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  sql:
    init:
      mode: always  # SQL 초기화 활성화
  devtools:
    restart:
      enabled: true  # 개발 도구로 자동 재시작 활성화

logging:
  level:
    org.hibernate.SQL: DEBUG   # (선택) Hibernate 쿼리 로깅 활성화
    org.springframework: DEBUG
server:
  port: 8081
springdoc:
  swagger-ui:
    urls:
      - name: Order Service
        url: https://order-api.emmotional-cart.click/v3/api-docs
      - name: Product Service
        url: https://product-api.emmotional-cart.click/v3/api-docs
      - name: Stock Service
        url: ${STOCK_SERVER_URL:http://localhost:9992}/v3/api-docs
      - name: Member Service
        url: https://member-api.emmotional-cart.click/v3/api-docs
      - name: Auth Service
        url: https://auth-api.emmotional-cart.click/v3/api-docs
aws:
  s3:
    access-key: test
    secret-key: test
app:
  allow-domains:
    - https://auth-api.emmotional-cart.click
    - https://member-api.emmotional-cart.click
    - https://product-api.emmotional-cart.click
    - https://order-api.emmotional-cart.click
