
spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: Kakao
            client-id: fc379f7f44f086c287618c49de7e366f
            client-secret: a2MFseY5A70id14t2DFS5FSOoXXVMatv
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope:
#              - account_email
              - profile_nickname
            client-authentication-method: client_secret_post
          naver:
            client-name: naver
            client-id: RUPtW98ZDcOmwOIVRibH
            client-secret: NB0KEonYg_
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  datasource:
    url: jdbc:mysql://localhost:3306/commerce
    username: root
    password: solhee1q2w3e4r!@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # (옵션: create, update, validate, none. 개발 시 `update` 추천)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  sql:
    init:
      mode: always  # SQL 초기화 활성화
  devtools:
    restart:
      enabled: true  # 개발 도구로 자동 재시작 활성화
  web:
    resources:
      add-mappings: false  # Spring Boot에서 정적 리소스를 제공하지 않도록 설정이 변경

logging:
  level:
    org.hibernate.SQL: DEBUG   # (선택) Hibernate 쿼리 로깅 활성화