spring:
  application:
    name: stock-service
  profiles:
    include:
      - common
    active: default
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/emotional_cart}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:1234}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        generate_statistics: true
        id:
          new_generator_mappings: true

server:
  port: 9992