spring:
  application:
    name: crawler
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecommerce?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
        generate_statistics: true
        id:
          new_generator_mappings: true

coupang:
  base-url: https://www.coupang.com
  category: ${coupang.base-url}/np/categories
  default-category: 186764 # 남녀 공용 의류
  default-category-url: ${coupang.category}/${coupang.default-category}
  default-category-name: 여성패션

redis:
  stand-alone:
    host: localhost
    port: 6378

