jwt:
  secret-key: dlsjtjzmfdlzjajtmxlaghkdlxldgkqtlek
  header-key: Authorization
app:
  allow-domains:
    - ${MEMBER_SERVER_URL:http://localhost:8081}
    - ${PRODUCT_SERVER_URL:http://localhost:8080}
    - ${ORDER_SERVER_URL:http://localhost:9999}
    - ${STOCK_SERVER_URL:http://localhost:9992}
    - ${AUTH_SERVER_URL:http://localhost:8082}
    - ${FRONT_SERVER_URL:http://localhost:3000}
    - ${FRONT_SERVER_ADMIN_URL:http://localhost:5173}
    - https://www.emmotional-cart.click/
    - https://auth-api.emmotional-cart.click
    - https://member-api.emmotional-cart.click
    - https://product-api.emmotional-cart.click
    - https://order-api.emmotional-cart.click
