name: Order 서비스 배포

env:
  AWS_REGION: ap-northeast-2                   # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: order-service           # set this to your Amazon ECR repository name
  ECS_SERVICE: order-service                 # set this to your Amazon ECS service name
  ECS_CLUSTER: ecommerce-ecs-cluster                 # set this to your Amazon ECS cluster name
  ECS_TASK_DEFINITION: .aws/order-service.json # set this to the path to your Amazon ECS task definition
  # file, e.g. .aws/task-definition.json
  CONTAINER_NAME: order-service-container     # set this to the name of the container in the
  # containerDefinitions section of your task definition

run-name: order-dev deploy by ${{ github.actor }} - ${{ github.run_number }}
on: 
  workflow_dispatch:
  
    inputs:
      branch:
        required: false
        default: 'deploy'
        type: string
        description: "빌드할 브랜치명"  
# develop 브랜치에 푸쉬 되었을 때 워크플로우가 실행됩니다.
# on:
#   push:
#     branches:
#       - develop # 해당 브랜치에 머지되면 이 워크플로우가 트리거 된다.

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'

    - name: Grant execute permission to Gradle wrapper
      run: |
        chmod +x gradlew

    - name: Build with Gradle (Skip Tests for Faster Build)
      run: |
        ./gradlew clean build -x test

    - name: Verify JAR File Exists
      run: |
        ls -lah order/build/libs/

      # 프로젝트에 주입할 환경변수를 S3 버킷에서 가져와서 프로젝트에 주입
      # 가져와서 이름을 변경함
    - name: Download Environment File from S3 bucket
      run: |
        aws s3 cp s3://innercircle-ecommerce-environment-file/common-dev.env .
        mv ./common-dev.env ./order/.env

#    - name: Set Up Docker Environments
#      id: docker-env
#      env:
#        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#        IMAGE_TAG: ${{ github.sha }}
#      run: |
#        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        cd order
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ${{ env.ECS_TASK_DEFINITION }}
        container-name: ${{ env.CONTAINER_NAME }}
        image: ${{ steps.build-image.outputs.image }}

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: ${{ env.ECS_SERVICE }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true